name: Build And Publish

on:
  push:
   branches:
     - master
  
  schedule:
   - cron: '*/15 * * * *'
  
  # manual trigger
  # workflow_dispatch:

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    strategy:
      matrix:
        node-version: [12.x]

    steps:

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v2

    - name: Environment Preparation
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Dependencies Installation
      working-directory: ./
      run: |
        npm install

    - name: Create env parameters
      working-directory: ./
      run: |
        touch .env
        echo BLOCKCHAIN_CONNECTION_STRING =${{ secrets.BLOCKCHAIN_CONNECTION_STRING }} >> .env

    - name: Build JSONs
      working-directory: ./
      run: |
        npm run start

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Kyactus
        author_email: materiadex@gmail.com
        message: "Build JSONs"
        add: " ./dist/*"
      env:
        GITHUB_TOKEN: ${{ secrets.COMMIT_AUTH_TOKEN }}
